#!/usr/bin/env python3
"""
EAGLE CAD Command Script (.scr) Generator & Builder
Generates EAGLE batch script files (.scr) for native automation inside EAGLE CAD or Fusion 360 Electronics GUI.
"""

import sys
import os
import argparse

class EagleScriptBuilder:
    def __init__(self):
        self.commands = []

    def set_grid(self, unit="MM", size=1.0, multiple=1):
        """Set grid unit and size."""
        self.commands.append(f"GRID {unit} {size} {multiple};")
        return self

    def set_layer(self, layer_name_or_number):
        """Set active drawing layer."""
        self.commands.append(f"LAYER {layer_name_or_number};")
        return self

    def add_component(self, deviceset_with_lib, name, x, y, rot="R0"):
        """Add a component to schematic or board layout."""
        self.commands.append(f"ADD {deviceset_with_lib} '{name}' {rot} ({x} {y});")
        return self

    def change_value(self, name, new_value):
        """Change value of a placed component."""
        self.commands.append(f"VALUE '{name}' '{new_value}';")
        return self

    def change_name(self, old_name, new_name):
        """Change designator name of a placed component."""
        self.commands.append(f"NAME '{old_name}' '{new_name}';")
        return self

    def draw_wire(self, x1, y1, x2, y2, width=0.254, layer=None):
        """Draw a wire/trace segment."""
        if layer:
            self.set_layer(layer)
        self.commands.append(f"WIRE {width} ({x1} {y1}) ({x2} {y2});")
        return self

    def place_via(self, x, y, drill=0.5, diameter=0.8, shape="ROUND"):
        """Place a via on the PCB layout."""
        self.commands.append(f"VIA {diameter} {shape} ({x} {y});")
        return self

    def add_text(self, text, x, y, size=1.0, layer=21):
        """Place text on a specific layer."""
        self.set_layer(layer)
        self.commands.append(f"TEXT '{text}' ({x} {y});")
        return self

    def add_custom_command(self, raw_cmd):
        """Add arbitrary raw EAGLE CAD command string."""
        if not raw_cmd.endswith(";"):
            raw_cmd += ";"
        self.commands.append(raw_cmd)
        return self

    def export_script(self, output_path):
        """Write compiled .scr script to file."""
        script_content = "# Compiled EAGLE CAD Script (.scr) generated by Antigravity Agentic Skill\n"
        script_content += "\n".join(self.commands) + "\n"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(script_content)
        return output_path

def main():
    parser = argparse.ArgumentParser(description="EAGLE CAD Command Script (.scr) Generator")
    parser.add_argument("-o", "--output", required=True, help="Output .scr file path")
    parser.add_argument("--add-component", nargs=4, metavar=("DEV_WITH_LIB", "NAME", "X", "Y"), help="Add component (e.g. C-US@adafruit C1 10 20)")
    parser.add_argument("--set-grid", default="MM 1.0", help="Set grid unit and size (default: 'MM 1.0')")

    args = parser.parse_args()

    builder = EagleScriptBuilder()
    grid_parts = args.set_grid.split()
    unit = grid_parts[0]
    size = float(grid_parts[1]) if len(grid_parts) > 1 else 1.0
    builder.set_grid(unit, size)

    if args.add_component:
        dev, name, x, y = args.add_component
        builder.add_component(dev, name, float(x), float(y))

    out_file = builder.export_script(args.output)
    print(f"Generated EAGLE CAD script file: '{out_file}'")

if __name__ == "__main__":
    main()
